version: '3.8'

services:
  backend:
    build: ./
    ports:
      - 5000:5000
    volumes:
      - ./app/:/app/
    depends_on:
      - mongo
    networks:
      - host

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - host

networks:
    host:
